from __future__ import annotations

from app.models.product import Product


COMMON_CAMERA_EXCLUSIONS = [
    "accessories only",
    "accessory only",
    "battery only",
    "body cap only",
    "box only",
    "broken",
    "camera accessories",
    "case only",
    "charger only",
    "empty box",
    "for parts",
    "lens only",
    "manual only",
    "not working",
    "parts only",
    "repair",
    "untested",
]


def _camera(
    *,
    product_id: str,
    brand: str,
    model: str,
    aliases: list[str],
    required_terms: list[str],
    exclusions: list[str] | None = None,
    variant: str | None = None,
    metadata: dict[str, str] | None = None,
) -> Product:
    return Product(
        id=product_id,
        category="cameras",
        category_label="Cameras",
        product_type="camera_body",
        brand=brand,
        model=model,
        variant=variant,
        aliases=aliases,
        required_terms=required_terms,
        excluded_terms=[*COMMON_CAMERA_EXCLUSIONS, *(exclusions or [])],
        metadata=metadata or {},
        active=True,
    )


def demand_camera_products() -> list[Product]:
    """Small catalog supplement chosen from recurring unresolved camera demand.

    Keep close model variants explicitly separated here. The normal camera
    accessory and condition filters still apply after a product resolves.
    """

    return [
        _camera(
            product_id="camera-canon-powershot-g7-x",
            brand="Canon",
            model="PowerShot G7 X",
            aliases=[
                "Canon PowerShot G7 X",
                "Canon PowerShot G7X",
                "Canon G7 X",
                "Canon G7X",
                "PowerShot G7 X",
                "PowerShot G7X",
                "Canon PowerShot G7X Digital Camera",
            ],
            required_terms=["canon", "g7x"],
            exclusions=[
                "g7 x ii",
                "g7x ii",
                "g7xii",
                "g7x2",
                "mark ii",
                "mark 2",
                "g7 x iii",
                "g7x iii",
                "g7xiii",
                "g7x3",
                "mark iii",
                "mark 3",
            ],
            metadata={"lens": "fixed", "sensor_format": "1-inch"},
        ),
        _camera(
            product_id="camera-panasonic-lumix-g9-body",
            brand="Panasonic",
            model="Lumix G9",
            variant="Body",
            aliases=[
                "Panasonic Lumix G9 Body",
                "Panasonic Lumix G9",
                "Panasonic G9 Body",
                "Panasonic G9",
                "Lumix G9 Body",
                "Lumix G9",
                "Panasonic DC-G9",
                "Panasonic DCG9",
                "Panasonic Lumix DC-G9",
                "Lumix DC-G9",
                "Panasonic Lumix G9 Mirrorless MFT Body, Black",
            ],
            required_terms=["panasonic", "g9"],
            exclusions=["g9 ii", "g9ii", "dc g9m2", "dc-g9m2", "dcg9m2"],
            metadata={"mount": "Micro Four Thirds", "sensor_format": "Micro Four Thirds"},
        ),
        _camera(
            product_id="camera-nikon-d300-body",
            brand="Nikon",
            model="D300",
            variant="Body",
            aliases=["Nikon D300 Body", "Nikon D300", "Nikon D300 DSLR"],
            required_terms=["nikon", "d300"],
            exclusions=["d300s", "d300 s"],
            metadata={"mount": "Nikon F", "sensor_format": "APS-C"},
        ),
        _camera(
            product_id="camera-nikon-d4-body",
            brand="Nikon",
            model="D4",
            variant="Body",
            aliases=["Nikon D4 Body", "Nikon D4", "Nikon D4 DSLR"],
            required_terms=["nikon", "d4"],
            exclusions=["d4s", "d4 s"],
            metadata={"mount": "Nikon F", "sensor_format": "Full frame"},
        ),
        _camera(
            product_id="camera-sony-cyber-shot-dsc-rx1r",
            brand="Sony",
            model="Cyber-shot DSC-RX1R",
            aliases=[
                "Sony Cyber-shot DSC-RX1R",
                "Sony Cyber-Shot DSC-RX1R",
                "Sony DSC-RX1R",
                "Sony RX1R",
                "Sony Cyber-shot RX1R",
            ],
            required_terms=["sony", "rx1r"],
            exclusions=[
                "rx1r ii",
                "rx1rii",
                "rx1r2",
                "rx1rm2",
                "dsc rx1rm2",
                "dsc-rx1rm2",
            ],
            metadata={"lens": "fixed", "sensor_format": "Full frame"},
        ),
        _camera(
            product_id="camera-sony-cyber-shot-dsc-rx1",
            brand="Sony",
            model="Cyber-shot DSC-RX1",
            aliases=[
                "Sony Cyber-shot DSC-RX1",
                "Sony Cyber-Shot DSC-RX1",
                "Sony DSC-RX1",
                "Sony RX1",
                "Sony Cyber-shot RX1",
            ],
            required_terms=["sony", "rx1"],
            exclusions=["rx1r", "dsc rx1r", "dsc-rx1r"],
            metadata={"lens": "fixed", "sensor_format": "Full frame"},
        ),
        _camera(
            product_id="camera-canon-powershot-g7",
            brand="Canon",
            model="PowerShot G7",
            aliases=[
                "Canon PowerShot G7",
                "Canon PowerShot G7 Digital Camera",
                "Canon G7 PowerShot",
            ],
            required_terms=["canon", "powershot", "g7"],
            exclusions=[
                "g7 x",
                "g7x",
                "g7 x ii",
                "g7xii",
                "g7 x iii",
                "g7xiii",
            ],
            metadata={"lens": "fixed", "sensor_format": "1/1.8-inch"},
        ),
        _camera(
            product_id="camera-olympus-stylus-1",
            brand="Olympus",
            model="Stylus 1",
            aliases=[
                "Olympus Stylus 1",
                "Olympus STYLUS 1",
                "Olympus Stylus 1 Digital Camera",
            ],
            required_terms=["olympus", "stylus", "1"],
            exclusions=["stylus 1s", "stylus1s"],
            metadata={"lens": "fixed", "sensor_format": "1/1.7-inch"},
        ),
        _camera(
            product_id="camera-nikon-d800-body",
            brand="Nikon",
            model="D800",
            variant="Body",
            aliases=["Nikon D800 Body", "Nikon D800", "Nikon D800 DSLR"],
            required_terms=["nikon", "d800"],
            exclusions=["d800e", "d800 e"],
            metadata={"mount": "Nikon F", "sensor_format": "Full frame"},
        ),
        _camera(
            product_id="camera-sony-cyber-shot-dsc-rx100",
            brand="Sony",
            model="Cyber-shot DSC-RX100",
            aliases=[
                "Sony Cyber-shot DSC-RX100",
                "Sony Cyber-Shot DSC-RX100",
                "Sony DSC-RX100",
                "Sony RX100",
                "Sony RX100 Black",
            ],
            required_terms=["sony", "rx100"],
            exclusions=[
                "rx100 ii",
                "rx100ii",
                "rx100m2",
                "rx100 iii",
                "rx100iii",
                "rx100m3",
                "rx100 iv",
                "rx100iv",
                "rx100m4",
                "rx100 v",
                "rx100v",
                "rx100m5",
                "rx100 vi",
                "rx100vi",
                "rx100m6",
                "rx100 vii",
                "rx100vii",
                "rx100m7",
            ],
            metadata={"lens": "fixed", "sensor_format": "1-inch"},
        ),
    ]
