import type { IndexedProduct } from "@/lib/indexedProducts";

export const indexedConsoleExtras: IndexedProduct[] = [
  {
    slug: "playstation-2",
    category: "consoles",
    title: "PlayStation 2",
    query: "Sony PlayStation 2",
    brand: "Sony",
    description: "Cleaner current used listings for a working Sony PlayStation 2 console.",
    buyingSummary: "A used PS2 is cheap enough to be fun, but marketplace results are full of games, controllers, shells, and untested systems. PriceSift keeps the target simple: a working console, not a pile of PS2-adjacent stuff.",
    buyingChecks: ["Confirm the console powers on and produces stable video output.", "Check the disc drive reads games reliably and the tray or lid works normally.", "Inspect controller and memory-card ports for damage.", "Confirm the power/video cables and controllers you expect are actually included."],
    commonTraps: ["games or controllers without the console", "untested or for-parts systems", "empty boxes and replacement shells"],
  },
  {
    slug: "playstation-3",
    category: "consoles",
    title: "PlayStation 3",
    query: "Sony PlayStation 3",
    brand: "Sony",
    description: "Cleaner current used listings for a working Sony PlayStation 3 console.",
    buyingSummary: "PS3 listings span several hardware revisions and a lot of heavily used systems. The exact revision matters less here than getting a complete, working console with healthy video output, storage, ports, and disc drive.",
    buyingChecks: ["Confirm normal startup and clean HDMI output.", "Test the Blu-ray drive with a known-good game or movie.", "Check USB ports, networking, storage, and controller pairing.", "Look for overheating, shutdown, repair, or reflow history in the listing."],
    commonTraps: ["games, controllers, and hard drives sold alone", "systems with overheating or disc-drive faults", "for-parts and repair listings"],
  },
  {
    slug: "playstation-4",
    category: "consoles",
    title: "PlayStation 4",
    query: "PlayStation 4",
    brand: "Sony",
    description: "Cleaner current used listings for the original Sony PlayStation 4 console.",
    buyingSummary: "The original PS4 can still be a good inexpensive used console when the price is meaningfully below newer hardware. Keep it separate from Slim and Pro listings and make sure the optical drive, HDMI output, storage, and controller connection are healthy.",
    buyingChecks: ["Confirm original PS4 rather than PS4 Slim or PS4 Pro.", "Test HDMI output, startup, networking, USB ports, and internal storage.", "Verify the disc drive reads and ejects normally.", "Listen for unusually loud fan behavior and check for shutdown or overheating disclosures."],
    commonTraps: ["PS4 Slim or PS4 Pro systems", "controller-only and game bundles without a console", "broken HDMI ports and for-parts units"],
  },
  {
    slug: "xbox-360",
    category: "consoles",
    title: "Xbox 360",
    query: "Xbox 360",
    brand: "Microsoft",
    description: "Cleaner current used listings for a working Microsoft Xbox 360 console.",
    buyingSummary: "Xbox 360 is old enough that condition matters more than cosmetics. A working disc drive, stable video output, healthy power behavior, and a clearly included console are more important than chasing the cheapest listing.",
    buyingChecks: ["Confirm the listing includes the console itself, not only games or controllers.", "Test video output and normal startup without hardware error lights.", "Verify the disc drive reads and ejects reliably.", "Check storage, controller sync, USB ports, and the included power supply."],
    commonTraps: ["game lots and controller bundles", "systems sold without the correct power supply", "repair, red-ring, and untested consoles"],
  },
  {
    slug: "xbox-one-s",
    category: "consoles",
    title: "Xbox One S",
    query: "Xbox One S",
    brand: "Microsoft",
    description: "Cleaner current used listings for a working Microsoft Xbox One S console.",
    buyingSummary: "The Xbox One S is easy to confuse with the newer Series S in marketplace titles. Make sure the listing is actually the older Xbox One-family console and verify the optical drive on disc-capable models.",
    buyingChecks: ["Confirm Xbox One S rather than Xbox Series S.", "Verify HDMI output, startup, networking, USB ports, and storage.", "Test the optical drive when present.", "Confirm controller, power cable, and HDMI cable are included if you need them."],
    commonTraps: ["Xbox Series S systems", "controllers and external drives", "broken HDMI or optical-drive units"],
  },
  {
    slug: "xbox-one-x",
    category: "consoles",
    title: "Xbox One X",
    query: "Xbox One X",
    brand: "Microsoft",
    description: "Cleaner current used listings for a working Microsoft Xbox One X console.",
    buyingSummary: "Xbox One X and Xbox Series X are annoyingly easy to mix up in used listings. Exact model identification is the first check, followed by video output, storage, disc drive, and normal thermal behavior.",
    buyingChecks: ["Confirm Xbox One X rather than Xbox Series X.", "Verify HDMI output, startup, networking, USB ports, and storage.", "Test the optical drive with a known-good disc.", "Check for overheating, shutdown, or fan-noise disclosures."],
    commonTraps: ["Xbox Series X systems", "controllers, expansion storage, and accessories", "for-parts or HDMI-fault consoles"],
  },
  {
    slug: "nintendo-gamecube",
    category: "consoles",
    title: "Nintendo GameCube",
    query: "Nintendo GameCube",
    brand: "Nintendo",
    description: "Cleaner current used listings for a working Nintendo GameCube console.",
    buyingSummary: "GameCube listings are full of games, controllers, cables, and replacement parts. A useful used-console listing should clearly include the system itself and should have a working optical drive and video output.",
    buyingChecks: ["Confirm the console itself is included.", "Test disc reading and normal spindle/laser behavior.", "Check video output, controller ports, memory-card slots, and power.", "Confirm the power supply and video cable are included if you need a ready-to-play setup."],
    commonTraps: ["games and controllers without a console", "replacement shells and optical-drive parts", "untested or disc-read-fault systems"],
  },
  {
    slug: "nintendo-wii",
    category: "consoles",
    title: "Nintendo Wii",
    query: "Nintendo Wii",
    brand: "Nintendo",
    description: "Cleaner current used listings for a working original Nintendo Wii console, excluding Wii U.",
    buyingSummary: "The original Wii is inexpensive and common, but used listings frequently mix the console with Wii U hardware, game lots, accessories, and incomplete bundles. PriceSift keeps Wii U out of this target entirely.",
    buyingChecks: ["Confirm original Wii rather than Wii U.", "Test disc reading, video output, controller sync, and normal startup.", "Check the sensor-bar and GameCube-port features if those matter to you.", "Confirm the power supply, sensor bar, video cable, and controllers actually included."],
    commonTraps: ["Wii U consoles and GamePads", "game lots and accessory bundles without a Wii", "missing power supplies, sensor bars, or controllers"],
  },
  {
    slug: "playstation-5-pro",
    category: "consoles",
    title: "PlayStation 5 Pro",
    query: "PlayStation 5 Pro",
    brand: "Sony",
    description: "Cleaner current used listings for the Sony PlayStation 5 Pro console.",
    buyingSummary: "PS5 Pro listings need strict model matching because base PS5 systems, Slim consoles, detachable disc drives, stands, and accessories can all share similar wording.",
    buyingChecks: ["Confirm PS5 Pro rather than original PS5 or PS5 Slim.", "Verify HDMI output, startup, networking, storage, USB ports, and normal fan behavior.", "Confirm whether a detachable disc drive is included when that matters to you.", "Check exactly which controller, stand, cables, and accessories are part of the sale."],
    commonTraps: ["base PS5 and PS5 Slim systems", "detachable disc drives sold alone", "stands, faceplates, boxes, and accessories"],
  },
];
