import type { AllIndexedProduct } from "@/lib/allIndexedProductTypes";

export const indexedProductExtras: AllIndexedProduct[] = [
  {
    slug: "canon-eos-rebel-t8i",
    category: "cameras",
    title: "Canon EOS Rebel T8i Body",
    query: "Canon EOS Rebel T8i Body",
    brand: "Canon",
    description: "Current cleaner used listings for the Canon EOS Rebel T8i DSLR body.",
    buyingSummary: "A used Rebel T8i can be a practical DSLR buy when the body is fully functional and priced well below newer alternatives. Exact identification matters because older Rebel bodies, kits, accessories, and damaged cameras often share very similar marketplace wording.",
    buyingChecks: [
      "Confirm the listing is the Rebel T8i / EOS 850D generation rather than an older T7i, T7, or another Rebel body.",
      "Inspect the EF/EF-S mount, mirror box, sensor area, viewfinder, and hot shoe for impact, corrosion, or obvious damage.",
      "Verify autofocus, shutter, rear screen and hinge, card slot, buttons, dials, ports, and battery compartment work normally.",
      "Check exactly what a kit includes; do not assume a pictured lens, battery, charger, or accessories are part of the sale.",
    ],
    commonTraps: [
      "older Rebel T7i, T7, and similar Canon DSLR bodies",
      "lens kits or accessories presented unclearly",
      "boxes, grips, chargers, and damaged or for-parts bodies",
    ],
  },
  {
    slug: "canon-eos-7d-mark-ii",
    category: "cameras",
    title: "Canon EOS 7D Mark II Body",
    query: "Canon EOS 7D Mark II Body",
    brand: "Canon",
    description: "Current cleaner used listings for the Canon EOS 7D Mark II DSLR body.",
    buyingSummary: "The EOS 7D Mark II can still be appealing used when you want a rugged APS-C DSLR, but many examples saw serious sports or wildlife use. Functional condition, shutter history, controls, card slots, and impact wear matter more than cosmetic polish.",
    buyingChecks: [
      "Confirm Mark II rather than the original EOS 7D or another Canon 7-series listing.",
      "Check shutter-count context when available and verify shutter, mirror, autofocus, and continuous shooting behave normally.",
      "Inspect the EF/EF-S mount, sensor area, viewfinder, hot shoe, battery compartment, ports, and body seams for impact or corrosion.",
      "Verify both card slots, rear display, buttons, joystick, dials, and connection ports work correctly.",
    ],
    commonTraps: [
      "original EOS 7D bodies",
      "heavily used or damaged sports/wildlife bodies",
      "battery grips, chargers, cages, boxes, and parts-only listings",
    ],
  },
  {
    slug: "sony-a7r-v",
    category: "cameras",
    title: "Sony A7R V Body",
    query: "Sony A7R V Body",
    brand: "Sony",
    description: "Current cleaner used listings for the Sony A7R V high-resolution full-frame mirrorless camera body.",
    buyingSummary: "The A7R V is expensive enough used that a suspiciously cheap listing is not where I would get adventurous. Exact model, sensor condition, stabilization, card slots, screen, EVF, and a clean functional test matter a lot more than a few scuffs on the body.",
    buyingChecks: [
      "Confirm A7R V rather than A7R IV, A7 V, or another Sony A7-series body.",
      "Inspect the sensor and E mount carefully and verify autofocus, IBIS, shutter, EVF, rear screen, and both card slots.",
      "Check the multi-angle screen mechanism, hot shoe, ports, battery compartment, buttons, and dials for damage or intermittent behavior.",
      "For an expensive body, ask for current proof that it powers up, records, writes to cards, and produces clean images without errors.",
    ],
    commonTraps: [
      "A7R IV and other Sony A7-series bodies",
      "cages, grips, batteries, boxes, and accessory-only listings",
      "damaged, high-wear, or for-parts camera bodies",
    ],
  },
  {
    slug: "panasonic-lumix-s5-ii",
    category: "cameras",
    title: "Panasonic Lumix S5 II Body",
    query: "Panasonic Lumix S5 II Body",
    brand: "Panasonic",
    description: "Current cleaner used listings for the Panasonic Lumix S5 II full-frame mirrorless camera body.",
    buyingSummary: "A used S5 II can be a strong value when the discount is real and the camera is healthy. The main trick is keeping the S5 II separate from the original S5, S5 IIX, lens kits, cages, and video accessories that tend to pile into the same search.",
    buyingChecks: [
      "Confirm S5 II rather than the original S5 or the S5 IIX.",
      "Inspect the L-mount and sensor, then verify autofocus, stabilization, shutter, EVF, articulated screen, and both card slots.",
      "Check HDMI, USB, audio ports, hot shoe, screen hinge, battery compartment, buttons, and dials for damage or looseness.",
      "If the camera was used heavily for video, ask for a current recording test and confirm card writing and output work normally.",
    ],
    commonTraps: [
      "original Lumix S5 or S5 IIX bodies",
      "lens kits and video rigs presented unclearly",
      "cages, handles, batteries, chargers, and damaged bodies",
    ],
  },
  {
    slug: "sony-rx10-iv",
    category: "cameras",
    title: "Sony RX10 IV",
    query: "Sony RX10 IV",
    brand: "Sony",
    description: "Current cleaner used listings for the Sony RX10 IV fixed-lens bridge camera.",
    buyingSummary: "The RX10 IV is a little different from an interchangeable-lens body because the lens is part of the camera. That makes lens condition and zoom behavior just as important as the sensor, controls, screen, EVF, and electronics.",
    buyingChecks: [
      "Confirm RX10 IV rather than RX10 III, RX10 II, or another RX-series camera.",
      "Check the built-in lens through its full zoom range for smooth movement, impact damage, haze, fungus, or obvious optical problems.",
      "Verify autofocus, stabilization, shutter, EVF, rear screen, card slot, flash, buttons, dials, ports, and battery compartment.",
      "Look closely for barrel damage or filter-ring impacts because the lens is not a cheap replaceable accessory on this camera.",
    ],
    commonTraps: [
      "older RX10 generations",
      "lens hoods, batteries, chargers, cases, and accessory bundles",
      "cameras with damaged or malfunctioning built-in lenses",
    ],
  },
  {
    slug: "nikon-zf",
    category: "cameras",
    title: "Nikon Zf Body",
    query: "Nikon Zf Body",
    brand: "Nikon",
    description: "Current cleaner used listings for the Nikon Zf full-frame mirrorless camera body.",
    buyingSummary: "The Nikon Zf is a straightforward used target as long as the listing is really the full-frame Zf and not the smaller Z fc or an accessory. Check the stuff that matters: sensor, mount, stabilization, screen, EVF, controls, card slots, and ports.",
    buyingChecks: [
      "Confirm Nikon Zf rather than Nikon Z fc.",
      "Inspect the Z mount and sensor, then verify autofocus, stabilization, shutter, EVF, articulated screen, and card operation.",
      "Check the mechanical dials, buttons, hot shoe, ports, screen hinge, and battery compartment for impact or intermittent behavior.",
      "Make sure any grip, lens, battery, charger, or other accessory shown is explicitly included rather than assumed from the photos.",
    ],
    commonTraps: [
      "Nikon Z fc bodies",
      "grips, cages, lenses, batteries, and accessory-only listings",
      "damaged or for-parts camera bodies",
    ],
  },
  {
    slug: "canon-eos-r8",
    category: "cameras",
    title: "Canon EOS R8 Body",
    query: "Canon EOS R8 Body",
    brand: "Canon",
    description: "Current cleaner used listings for the Canon EOS R8 full-frame mirrorless camera body.",
    buyingSummary: "A used EOS R8 makes sense when the price is far enough below new to justify giving up the fresh warranty. Exact matching matters because R-series bodies, RF lenses, kits, cages, and damaged cameras can all share the same few words in a marketplace title.",
    buyingChecks: [
      "Confirm EOS R8 rather than R7, R10, RP, R6, or another Canon RF body.",
      "Inspect the RF mount and sensor and verify autofocus, shutter, EVF, articulated screen, and card slot.",
      "Check the screen hinge, hot shoe, USB/HDMI ports, microphone/headphone connections, buttons, dials, and battery compartment.",
      "Confirm whether a pictured lens, battery, charger, or kit accessory is actually included in the sale.",
    ],
    commonTraps: [
      "other Canon EOS R-series bodies",
      "RF lenses, cages, grips, and kit accessories",
      "damaged, incomplete, or for-parts bodies",
    ],
  },
  {
    slug: "canon-eos-rebel-t7",
    category: "cameras",
    title: "Canon EOS Rebel T7 Body",
    query: "Canon EOS Rebel T7 Body",
    brand: "Canon",
    description: "Current cleaner used listings for the Canon EOS Rebel T7 DSLR body.",
    buyingSummary: "The Rebel T7 is cheap enough that condition and included gear can swing whether used is actually a deal. The biggest headache is separating the T7 from older Rebel models, lens kits, accessories, and listings where the camera is damaged or incomplete.",
    buyingChecks: [
      "Confirm Rebel T7 / EOS 2000D rather than T7i, T6, T6i, or another Rebel body.",
      "Inspect the EF/EF-S mount, mirror box, sensor area, viewfinder, hot shoe, and battery compartment.",
      "Verify autofocus, shutter, rear screen, card slot, buttons, dial, flash, and ports work normally.",
      "Check exactly what is included in kit listings; a lens, battery, charger, strap, or bag should not be assumed from the pictures.",
    ],
    commonTraps: [
      "T7i, T6, T6i, and other similar Rebel bodies",
      "lens-only or accessory-heavy kits",
      "empty boxes, chargers, grips, and damaged bodies",
    ],
  },
  {
    slug: "fujifilm-x-t1",
    category: "cameras",
    title: "Fujifilm X-T1 Body",
    query: "Fujifilm X-T1 Body",
    brand: "Fujifilm",
    description: "Current cleaner used listings for the Fujifilm X-T1 APS-C mirrorless camera body.",
    buyingSummary: "The X-T1 is old enough now that a working, honest example matters more than finding one that looks museum-clean. Pay attention to the sensor, X mount, EVF, rear screen, dials, buttons, ports, battery compartment, and signs of impact or corrosion.",
    buyingChecks: [
      "Confirm X-T1 rather than X-T10, X-T2, X-T20, or another Fujifilm X-series body.",
      "Inspect the X mount and sensor and verify autofocus, shutter, EVF, rear screen, card slot, buttons, and command dials.",
      "Check the top mechanical dials and switches for normal detents and reliable operation.",
      "Inspect the hot shoe, ports, battery compartment, screws, and body seams for corrosion, impact, or rough repair work.",
    ],
    commonTraps: [
      "X-T10, X-T2, and other similarly named Fujifilm bodies",
      "grips, thumb rests, batteries, chargers, and accessory-only listings",
      "older bodies with undisclosed control or electronic faults",
    ],
  },
  {
    slug: "amd-ryzen-7-5800x3d",
    category: "cpus",
    title: "AMD Ryzen 7 5800X3D",
    query: "AMD Ryzen 7 5800X3D",
    brand: "AMD",
    description: "Current cleaner used listings for the AMD Ryzen 7 5800X3D AM4 desktop processor.",
    buyingSummary: "The 5800X3D is still a desirable AM4 upgrade, which also means used pricing can stay surprisingly stubborn. Make sure the listing is the actual 5800X3D CPU, not a nearby Ryzen chip, motherboard bundle, cooler, empty box, or damaged processor.",
    buyingChecks: [
      "Confirm Ryzen 7 5800X3D rather than 5800X, 5700X3D, 7800X3D, or another nearby Ryzen model.",
      "Inspect the AM4 pins closely for bends, missing pins, corrosion, thermal-paste contamination, or repair work.",
      "Ask for a current system screenshot or test that identifies the CPU correctly and shows it running under load without crashes.",
      "Remember that the 5800X3D is AM4; verify your motherboard BIOS support before treating a good CPU price as a good upgrade price.",
    ],
    commonTraps: [
      "Ryzen 7 5800X, 5700X3D, and other nearby Ryzen models",
      "motherboard bundles, coolers, boxes, and complete-PC listings",
      "processors with bent or repaired pins or other physical damage",
    ],
  },
];
